name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: newestfenics
        environment-file: conda_env_no_cuda.yml
        python-version: 3.9.18
        auto-activate-base: false
    - name: Install other dependencies
      run: |
        conda install -c bioconda tbb=2020.2
        pip install git+https://github.com/g-peery/sanity_research_utils.git git+https://github.com/g-peery/moola.git
        pip install -e .
        pip install pdoc

      # build your documentation into docs/.
      - run: pdoc gel --math -o docs/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
