name: Attempt installation and verify help messages work

on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: newestfenics
        environment-file: conda_env_no_cuda.yml
        python-version: 3.9.18
        auto-activate-base: false
    - name: Install other dependencies
      run: |
        pip install git+https://github.com/g-peery/sanity_research_utils.git git+https://github.com/g-peery/moola.git
        pip install -e .
    - name: Test scripts
      run: |
        forward --help
        inverse --help
        downsample_mesh --help
        get_u --help
        get_kinematics_mesh --help
        get_veh --help
    
